### ISSUE TITLE
Add a license to repo

### ISSUE THREAD

**Issue by johnDeSilencio** [NotAPenguin0/andromeda-rs#13]
Hello, @NotAPenguin0! I hope you're doing well!

I just read [your article on writing an event system in Rust from scratch](https://www.notapenguin.blog/posts/rust-event-systems/) and I loved it!

I noticed that your repo doesn't have a license associated with it? I really would love to incorporate some of your scheduler code into my own work at some point (giving you credit, of course) but don't want to do so if you haven't explicitly open-sourced the code.

Can you add an [open source license](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) to this repo? For example, [`MIT`](https://opensource.org/license/MIT) , [`Apache-2.0`](https://opensource.org/license/apache-2-0), or both.

Thanks again for your great work!

- Nick

**Comment by NotAPenguin0** [comment]
Hi, thanks a lot for the kind message!

I'm really glad to see you enjoyed the article (before the domain expires in a few weeks). I've licensed the repository under the MIT license. Hopefully the code you need turns out to be useful.

All the best,

Michiel

**Comment by johnDeSilencio** [comment]
Amazing! Thank you for such a quick turnaround. Going to hack around with your event bus tonight.

Cheers, and all the best to you!

- Nick
